spring.application.name=demo4
server.port=${PORT:8080}

# Если переменная DATABASE_URL пустая, Spring попробует найти другие.
# Если вообще ничего нет, он упадет с понятной ошибкой.
spring.datasource.url=${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:sa}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.points.per-answer=1
