spring.datasource.url=jdbc:postgresql://localhost:5432/demo4
spring.datasource.username=demo4
spring.datasource.password=demo4
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
