spring.application.name=demo4
server.port=${PORT:8080}

# Явно указываем ключи, которые вы задали в панели Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Эти настройки заставят Hibernate создать таблицы автоматически
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Чтобы приложение не упало, если база временно недоступна при запуске
spring.datasource.hikari.initialization-fail-timeout=0
